// Code generated by libopenapi generator/golang. DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"
)

type IDName struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type IssueStatusSimple struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	IsClosed bool   `json:"is_closed"`
}

type CustomFieldValue_ValueUnion struct {
	Raw json.RawMessage
}

func (u *CustomFieldValue_ValueUnion) UnmarshalJSON(data []byte) error {
	u.Raw = append(u.Raw[:0], data...)
	return nil
}

func (u CustomFieldValue_ValueUnion) MarshalJSON() ([]byte, error) {
	if len(u.Raw) == 0 {
		return []byte("null"), nil
	}
	return u.Raw, nil
}

func (u CustomFieldValue_ValueUnion) IsZero() bool {
	return len(u.Raw) == 0
}

func (u CustomFieldValue_ValueUnion) Bytes() []byte {
	return append([]byte(nil), u.Raw...)
}

type CustomFieldValue struct {
	ID       int                         `json:"id"`
	Name     string                      `json:"name"`
	Multiple *bool                       `json:"multiple,omitempty"`
	Value    CustomFieldValue_ValueUnion `json:"value"`
}

type Attachment struct {
	ID           int       `json:"id"`
	Filename     string    `json:"filename"`
	Filesize     int       `json:"filesize"`
	ContentType  *string   `json:"content_type"`
	Description  *string   `json:"description"`
	ContentURL   string    `json:"content_url"`
	ThumbnailURL *string   `json:"thumbnail_url,omitempty"`
	Author       *IDName   `json:"author,omitempty"`
	CreatedOn    time.Time `json:"created_on"`
}

type IssueSimple_Parent struct {
	ID *int `json:"id,omitempty"`
}

type IssueSimple_Relations_Item_RelationType string

const (
	IssueSimple_Relations_Item_RelationTypeRelates    IssueSimple_Relations_Item_RelationType = "relates"
	IssueSimple_Relations_Item_RelationTypeDuplicates IssueSimple_Relations_Item_RelationType = "duplicates"
	IssueSimple_Relations_Item_RelationTypeDuplicated IssueSimple_Relations_Item_RelationType = "duplicated"
	IssueSimple_Relations_Item_RelationTypeBlocks     IssueSimple_Relations_Item_RelationType = "blocks"
	IssueSimple_Relations_Item_RelationTypeBlocked    IssueSimple_Relations_Item_RelationType = "blocked"
	IssueSimple_Relations_Item_RelationTypePrecedes   IssueSimple_Relations_Item_RelationType = "precedes"
	IssueSimple_Relations_Item_RelationTypeFollows    IssueSimple_Relations_Item_RelationType = "follows"
	IssueSimple_Relations_Item_RelationTypeCopiedTo   IssueSimple_Relations_Item_RelationType = "copied_to"
	IssueSimple_Relations_Item_RelationTypeCopiedFrom IssueSimple_Relations_Item_RelationType = "copied_from"
)

type IssueSimple_Relations_Item struct {
	ID           *int                                     `json:"id,omitempty"`
	IssueID      *int                                     `json:"issue_id,omitempty"`
	IssueToID    *int                                     `json:"issue_to_id,omitempty"`
	RelationType *IssueSimple_Relations_Item_RelationType `json:"relation_type,omitempty"`
	Delay        *int                                     `json:"delay,omitempty"`
}

type IssueSimple struct {
	ID                  int                          `json:"id"`
	Project             *IDName                      `json:"project,omitempty"`
	Tracker             *IDName                      `json:"tracker,omitempty"`
	Status              *IssueStatusSimple           `json:"status,omitempty"`
	Priority            *IDName                      `json:"priority,omitempty"`
	Author              *IDName                      `json:"author,omitempty"`
	AssignedTo          *IDName                      `json:"assigned_to,omitempty"`
	Category            *IDName                      `json:"category,omitempty"`
	FixedVersion        *IDName                      `json:"fixed_version,omitempty"`
	Parent              *IssueSimple_Parent          `json:"parent,omitempty"`
	Subject             string                       `json:"subject"`
	Description         *string                      `json:"description"`
	StartDate           *string                      `json:"start_date"`
	DueDate             *string                      `json:"due_date"`
	DoneRatio           int                          `json:"done_ratio"`
	IsPrivate           bool                         `json:"is_private"`
	EstimatedHours      *float64                     `json:"estimated_hours"`
	TotalEstimatedHours *float64                     `json:"total_estimated_hours"`
	SpentHours          *float64                     `json:"spent_hours,omitempty"`
	TotalSpentHours     *float64                     `json:"total_spent_hours,omitempty"`
	CustomFields        []CustomFieldValue           `json:"custom_fields,omitempty"`
	CreatedOn           time.Time                    `json:"created_on"`
	UpdatedOn           time.Time                    `json:"updated_on"`
	ClosedOn            *time.Time                   `json:"closed_on"`
	Attachments         []Attachment                 `json:"attachments,omitempty"`
	Relations           []IssueSimple_Relations_Item `json:"relations,omitempty"`
}

type CustomFields_Item_ValueUnion struct {
	Raw json.RawMessage
}

func (u *CustomFields_Item_ValueUnion) UnmarshalJSON(data []byte) error {
	u.Raw = append(u.Raw[:0], data...)
	return nil
}

func (u CustomFields_Item_ValueUnion) MarshalJSON() ([]byte, error) {
	if len(u.Raw) == 0 {
		return []byte("null"), nil
	}
	return u.Raw, nil
}

func (u CustomFields_Item_ValueUnion) IsZero() bool {
	return len(u.Raw) == 0
}

func (u CustomFields_Item_ValueUnion) Bytes() []byte {
	return append([]byte(nil), u.Raw...)
}

type CustomFields_Item struct {
	ID    int                           `json:"id"`
	Value *CustomFields_Item_ValueUnion `json:"value,omitempty"`
}

type CustomFields []CustomFields_Item

type CustomFieldValues_AdditionalPropertyUnion struct {
	Raw json.RawMessage
}

func (u *CustomFieldValues_AdditionalPropertyUnion) UnmarshalJSON(data []byte) error {
	u.Raw = append(u.Raw[:0], data...)
	return nil
}

func (u CustomFieldValues_AdditionalPropertyUnion) MarshalJSON() ([]byte, error) {
	if len(u.Raw) == 0 {
		return []byte("null"), nil
	}
	return u.Raw, nil
}

func (u CustomFieldValues_AdditionalPropertyUnion) IsZero() bool {
	return len(u.Raw) == 0
}

func (u CustomFieldValues_AdditionalPropertyUnion) Bytes() []byte {
	return append([]byte(nil), u.Raw...)
}

type CustomFieldValues struct {
	AdditionalProperties map[string]CustomFieldValues_AdditionalPropertyUnion `json:"-"`
}

func (m *CustomFieldValues) UnmarshalJSON(data []byte) error {
	type Alias CustomFieldValues
	var known Alias
	if err := json.Unmarshal(data, &known); err != nil {
		return err
	}
	*m = CustomFieldValues(known)
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if len(raw) == 0 {
		return nil
	}
	m.AdditionalProperties = make(map[string]CustomFieldValues_AdditionalPropertyUnion, len(raw))
	for key, value := range raw {
		var decoded CustomFieldValues_AdditionalPropertyUnion
		if err := json.Unmarshal(value, &decoded); err != nil {
			return err
		}
		m.AdditionalProperties[key] = decoded
	}
	return nil
}

func (m CustomFieldValues) MarshalJSON() ([]byte, error) {
	type Alias CustomFieldValues
	encoded, err := json.Marshal(Alias(m))
	if err != nil {
		return nil, err
	}
	var object map[string]json.RawMessage
	if err := json.Unmarshal(encoded, &object); err != nil {
		return nil, err
	}
	for key, value := range m.AdditionalProperties {
		encodedValue, err := json.Marshal(value)
		if err != nil {
			return nil, err
		}
		object[key] = encodedValue
	}
	return json.Marshal(object)
}

type Uploads_Item struct {
	Token       *string `json:"token,omitempty"`
	Filename    *string `json:"filename,omitempty"`
	Description *string `json:"description,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
}

type Uploads []Uploads_Item

type Errors struct {
	Errors []string `json:"errors"`
}

type Issue_Parent struct {
	ID *int `json:"id,omitempty"`
}

type Issue_Changesets_Item struct {
	Revision    *string    `json:"revision,omitempty"`
	User        *IDName    `json:"user,omitempty"`
	Comments    *string    `json:"comments,omitempty"`
	CommittedOn *time.Time `json:"committed_on,omitempty"`
}

type Issue_Children_Item struct {
	ID      *int    `json:"id,omitempty"`
	Tracker *IDName `json:"tracker,omitempty"`
	Subject *string `json:"subject,omitempty"`
}

type Issue_Relations_Item_RelationType string

const (
	Issue_Relations_Item_RelationTypeRelates    Issue_Relations_Item_RelationType = "relates"
	Issue_Relations_Item_RelationTypeDuplicates Issue_Relations_Item_RelationType = "duplicates"
	Issue_Relations_Item_RelationTypeDuplicated Issue_Relations_Item_RelationType = "duplicated"
	Issue_Relations_Item_RelationTypeBlocks     Issue_Relations_Item_RelationType = "blocks"
	Issue_Relations_Item_RelationTypeBlocked    Issue_Relations_Item_RelationType = "blocked"
	Issue_Relations_Item_RelationTypePrecedes   Issue_Relations_Item_RelationType = "precedes"
	Issue_Relations_Item_RelationTypeFollows    Issue_Relations_Item_RelationType = "follows"
	Issue_Relations_Item_RelationTypeCopiedTo   Issue_Relations_Item_RelationType = "copied_to"
	Issue_Relations_Item_RelationTypeCopiedFrom Issue_Relations_Item_RelationType = "copied_from"
)

type Issue_Relations_Item struct {
	ID           *int                               `json:"id,omitempty"`
	IssueID      *int                               `json:"issue_id,omitempty"`
	IssueToID    *int                               `json:"issue_to_id,omitempty"`
	RelationType *Issue_Relations_Item_RelationType `json:"relation_type,omitempty"`
	Delay        *int                               `json:"delay,omitempty"`
}

type Issue_Journals_Item_Details_Item struct {
	Property *string `json:"property,omitempty"`
	Name     *string `json:"name,omitempty"`
	OldValue *string `json:"old_value,omitempty"`
	NewValue *string `json:"new_value,omitempty"`
}

type Issue_Journals_Item struct {
	ID           *int                               `json:"id,omitempty"`
	User         *IDName                            `json:"user,omitempty"`
	Notes        *string                            `json:"notes,omitempty"`
	CreatedOn    *time.Time                         `json:"created_on,omitempty"`
	UpdatedOn    *time.Time                         `json:"updated_on,omitempty"`
	UpdatedBy    *IDName                            `json:"updated_by,omitempty"`
	PrivateNotes *bool                              `json:"private_notes,omitempty"`
	Details      []Issue_Journals_Item_Details_Item `json:"details,omitempty"`
}

type Issue struct {
	ID                  int                     `json:"id"`
	Project             *IDName                 `json:"project,omitempty"`
	Tracker             *IDName                 `json:"tracker,omitempty"`
	Status              *IssueStatusSimple      `json:"status,omitempty"`
	Priority            *IDName                 `json:"priority,omitempty"`
	Author              *IDName                 `json:"author,omitempty"`
	AssignedTo          *IDName                 `json:"assigned_to,omitempty"`
	Category            *IDName                 `json:"category,omitempty"`
	FixedVersion        *IDName                 `json:"fixed_version,omitempty"`
	Parent              *Issue_Parent           `json:"parent,omitempty"`
	Subject             string                  `json:"subject"`
	Description         *string                 `json:"description"`
	StartDate           *string                 `json:"start_date"`
	DueDate             *string                 `json:"due_date"`
	DoneRatio           int                     `json:"done_ratio"`
	IsPrivate           bool                    `json:"is_private"`
	EstimatedHours      *float64                `json:"estimated_hours"`
	TotalEstimatedHours *float64                `json:"total_estimated_hours"`
	SpentHours          *float64                `json:"spent_hours,omitempty"`
	TotalSpentHours     *float64                `json:"total_spent_hours,omitempty"`
	CustomFields        []CustomFieldValue      `json:"custom_fields,omitempty"`
	CreatedOn           time.Time               `json:"created_on"`
	UpdatedOn           time.Time               `json:"updated_on"`
	ClosedOn            *time.Time              `json:"closed_on"`
	Changesets          []Issue_Changesets_Item `json:"changesets,omitempty"`
	Children            []Issue_Children_Item   `json:"children,omitempty"`
	Attachments         []Attachment            `json:"attachments,omitempty"`
	Relations           []Issue_Relations_Item  `json:"relations,omitempty"`
	Journals            []Issue_Journals_Item   `json:"journals,omitempty"`
	Watchers            []IDName                `json:"watchers,omitempty"`
	AllowedStatuses     []IssueStatusSimple     `json:"allowed_statuses,omitempty"`
}

type ProjectSimple struct {
	ID                  int                `json:"id"`
	Name                string             `json:"name"`
	Identifier          string             `json:"identifier"`
	Description         *string            `json:"description"`
	Homepage            *string            `json:"homepage"`
	Parent              *IDName            `json:"parent,omitempty"`
	Status              int                `json:"status"`
	IsPublic            bool               `json:"is_public"`
	InheritMembers      bool               `json:"inherit_members"`
	CustomFields        []CustomFieldValue `json:"custom_fields,omitempty"`
	Trackers            []IDName           `json:"trackers,omitempty"`
	IssueCategories     []IDName           `json:"issue_categories,omitempty"`
	TimeEntryActivities []IDName           `json:"time_entry_activities,omitempty"`
	EnabledModules      []IDName           `json:"enabled_modules,omitempty"`
	IssueCustomFields   []IDName           `json:"issue_custom_fields,omitempty"`
	CreatedOn           time.Time          `json:"created_on"`
	UpdatedOn           time.Time          `json:"updated_on"`
}

type Project struct {
	ID                  int                `json:"id"`
	Name                string             `json:"name"`
	Identifier          string             `json:"identifier"`
	Description         *string            `json:"description"`
	Homepage            *string            `json:"homepage"`
	Parent              *IDName            `json:"parent,omitempty"`
	Status              int                `json:"status"`
	IsPublic            bool               `json:"is_public"`
	InheritMembers      bool               `json:"inherit_members"`
	DefaultVersion      *IDName            `json:"default_version,omitempty"`
	DefaultAssignee     *IDName            `json:"default_assignee,omitempty"`
	CustomFields        []CustomFieldValue `json:"custom_fields,omitempty"`
	Trackers            []IDName           `json:"trackers,omitempty"`
	IssueCategories     []IDName           `json:"issue_categories,omitempty"`
	TimeEntryActivities []IDName           `json:"time_entry_activities,omitempty"`
	EnabledModules      []IDName           `json:"enabled_modules,omitempty"`
	IssueCustomFields   []IDName           `json:"issue_custom_fields,omitempty"`
	CreatedOn           time.Time          `json:"created_on"`
	UpdatedOn           time.Time          `json:"updated_on"`
}

type MembershipRole struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Inherited *bool  `json:"inherited,omitempty"`
}

type Membership struct {
	ID      int              `json:"id"`
	Project IDName           `json:"project"`
	User    *IDName          `json:"user,omitempty"`
	Group   *IDName          `json:"group,omitempty"`
	Roles   []MembershipRole `json:"roles"`
}

type UserSimple struct {
	ID              int                `json:"id"`
	Login           string             `json:"login"`
	Admin           bool               `json:"admin"`
	Firstname       string             `json:"firstname"`
	Lastname        string             `json:"lastname"`
	Mail            string             `json:"mail"`
	CreatedOn       time.Time          `json:"created_on"`
	UpdatedOn       time.Time          `json:"updated_on"`
	LastLoginOn     *time.Time         `json:"last_login_on"`
	PasswdChangedOn *time.Time         `json:"passwd_changed_on"`
	AvatarURL       *string            `json:"avatar_url,omitempty"`
	TwofaScheme     *string            `json:"twofa_scheme"`
	Status          int                `json:"status"`
	AuthSource      *IDName            `json:"auth_source,omitempty"`
	CustomFields    []CustomFieldValue `json:"custom_fields,omitempty"`
}

type Pref_CommentsSorting string

const (
	Pref_CommentsSortingAsc  Pref_CommentsSorting = "asc"
	Pref_CommentsSortingDesc Pref_CommentsSorting = "desc"
)

type Pref_TextareaFont string

const (
	Pref_TextareaFontMonospace    Pref_TextareaFont = "monospace"
	Pref_TextareaFontProportional Pref_TextareaFont = "proportional"
)

type Pref_HistoryDefaultTab string

const (
	Pref_HistoryDefaultTabNotes          Pref_HistoryDefaultTab = "notes"
	Pref_HistoryDefaultTabHistory        Pref_HistoryDefaultTab = "history"
	Pref_HistoryDefaultTabProperties     Pref_HistoryDefaultTab = "properties"
	Pref_HistoryDefaultTabTimeEntries    Pref_HistoryDefaultTab = "time_entries"
	Pref_HistoryDefaultTabChangesets     Pref_HistoryDefaultTab = "changesets"
	Pref_HistoryDefaultTabLastTabVisited Pref_HistoryDefaultTab = "last_tab_visited"
)

type Pref_AutoWatchOn_Item string

const (
	Pref_AutoWatchOn_ItemIssueCreated       Pref_AutoWatchOn_Item = "issue_created"
	Pref_AutoWatchOn_ItemIssueContributedTo Pref_AutoWatchOn_Item = "issue_contributed_to"
	Pref_AutoWatchOn_ItemIssueAssignedToMe  Pref_AutoWatchOn_Item = "issue_assigned_to_me"
)

type Pref struct {
	HideMail                      *bool                   `json:"hide_mail,omitempty"`
	TimeZone                      *string                 `json:"time_zone,omitempty"`
	CommentsSorting               *Pref_CommentsSorting   `json:"comments_sorting,omitempty"`
	WarnOnLeavingUnsaved          *bool                   `json:"warn_on_leaving_unsaved,omitempty"`
	NoSelfNotified                *bool                   `json:"no_self_notified,omitempty"`
	NotifyAboutHighPriorityIssues *bool                   `json:"notify_about_high_priority_issues,omitempty"`
	TextareaFont                  *Pref_TextareaFont      `json:"textarea_font,omitempty"`
	RecentlyUsedProjects          *int                    `json:"recently_used_projects,omitempty"`
	HistoryDefaultTab             *Pref_HistoryDefaultTab `json:"history_default_tab,omitempty"`
	ToolbarLanguageOptions        *string                 `json:"toolbar_language_options,omitempty"`
	DefaultIssueQuery             *int                    `json:"default_issue_query,omitempty"`
	DefaultProjectQuery           *int                    `json:"default_project_query,omitempty"`
	AutoWatchOn                   []Pref_AutoWatchOn_Item `json:"auto_watch_on,omitempty"`
}

type User_Memberships_Item_Roles_Item struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Inherited *bool  `json:"inherited,omitempty"`
}

type User_Memberships_Item struct {
	ID      int                                `json:"id"`
	Project IDName                             `json:"project"`
	Roles   []User_Memberships_Item_Roles_Item `json:"roles"`
}

type User struct {
	ID              int                     `json:"id"`
	Login           string                  `json:"login"`
	Admin           *bool                   `json:"admin,omitempty"`
	Firstname       string                  `json:"firstname"`
	Lastname        string                  `json:"lastname"`
	Mail            *string                 `json:"mail,omitempty"`
	CreatedOn       time.Time               `json:"created_on"`
	UpdatedOn       time.Time               `json:"updated_on"`
	LastLoginOn     *time.Time              `json:"last_login_on"`
	PasswdChangedOn *time.Time              `json:"passwd_changed_on"`
	AvatarURL       *string                 `json:"avatar_url,omitempty"`
	TwofaScheme     *string                 `json:"twofa_scheme,omitempty"`
	APIKey          *string                 `json:"api_key,omitempty"`
	Status          *int                    `json:"status,omitempty"`
	CustomFields    []CustomFieldValue      `json:"custom_fields,omitempty"`
	AuthSource      *IDName                 `json:"auth_source,omitempty"`
	Groups          []IDName                `json:"groups,omitempty"`
	Memberships     []User_Memberships_Item `json:"memberships,omitempty"`
}

type TimeEntry_Issue struct {
	ID int `json:"id"`
}

type TimeEntry struct {
	ID           int                `json:"id"`
	Project      *IDName            `json:"project,omitempty"`
	Issue        *TimeEntry_Issue   `json:"issue,omitempty"`
	User         *IDName            `json:"user,omitempty"`
	Activity     *IDName            `json:"activity,omitempty"`
	Hours        float64            `json:"hours"`
	Comments     *string            `json:"comments"`
	SpentOn      string             `json:"spent_on"`
	CreatedOn    time.Time          `json:"created_on"`
	UpdatedOn    time.Time          `json:"updated_on"`
	CustomFields []CustomFieldValue `json:"custom_fields,omitempty"`
}

type NewsComment struct {
	ID      int     `json:"id"`
	Author  *IDName `json:"author,omitempty"`
	Content string  `json:"content"`
}

type News struct {
	ID          int           `json:"id"`
	Project     *IDName       `json:"project,omitempty"`
	Author      *IDName       `json:"author,omitempty"`
	Title       string        `json:"title"`
	Summary     *string       `json:"summary,omitempty"`
	Description string        `json:"description"`
	CreatedOn   time.Time     `json:"created_on"`
	Attachments []Attachment  `json:"attachments,omitempty"`
	Comments    []NewsComment `json:"comments,omitempty"`
}

type IssueRelation_RelationType string

const (
	IssueRelation_RelationTypeRelates    IssueRelation_RelationType = "relates"
	IssueRelation_RelationTypeDuplicates IssueRelation_RelationType = "duplicates"
	IssueRelation_RelationTypeDuplicated IssueRelation_RelationType = "duplicated"
	IssueRelation_RelationTypeBlocks     IssueRelation_RelationType = "blocks"
	IssueRelation_RelationTypeBlocked    IssueRelation_RelationType = "blocked"
	IssueRelation_RelationTypePrecedes   IssueRelation_RelationType = "precedes"
	IssueRelation_RelationTypeFollows    IssueRelation_RelationType = "follows"
	IssueRelation_RelationTypeCopiedTo   IssueRelation_RelationType = "copied_to"
	IssueRelation_RelationTypeCopiedFrom IssueRelation_RelationType = "copied_from"
)

type IssueRelation struct {
	ID           int                        `json:"id"`
	IssueID      int                        `json:"issue_id"`
	IssueToID    int                        `json:"issue_to_id"`
	RelationType IssueRelation_RelationType `json:"relation_type"`
	Delay        *int                       `json:"delay"`
}

type VersionSimple_Status string

const (
	VersionSimple_StatusOpen   VersionSimple_Status = "open"
	VersionSimple_StatusLocked VersionSimple_Status = "locked"
	VersionSimple_StatusClosed VersionSimple_Status = "closed"
)

type VersionSimple_Sharing string

const (
	VersionSimple_SharingNone        VersionSimple_Sharing = "none"
	VersionSimple_SharingDescendants VersionSimple_Sharing = "descendants"
	VersionSimple_SharingHierarchy   VersionSimple_Sharing = "hierarchy"
	VersionSimple_SharingTree        VersionSimple_Sharing = "tree"
	VersionSimple_SharingSystem      VersionSimple_Sharing = "system"
)

type VersionSimple struct {
	ID            int                   `json:"id"`
	Project       *IDName               `json:"project,omitempty"`
	Name          string                `json:"name"`
	Description   *string               `json:"description"`
	Status        VersionSimple_Status  `json:"status"`
	DueDate       *string               `json:"due_date"`
	Sharing       VersionSimple_Sharing `json:"sharing"`
	WikiPageTitle *string               `json:"wiki_page_title"`
	CustomFields  []CustomFieldValue    `json:"custom_fields,omitempty"`
	CreatedOn     time.Time             `json:"created_on"`
	UpdatedOn     time.Time             `json:"updated_on"`
}

type Version_Status string

const (
	Version_StatusOpen   Version_Status = "open"
	Version_StatusLocked Version_Status = "locked"
	Version_StatusClosed Version_Status = "closed"
)

type Version_Sharing string

const (
	Version_SharingNone        Version_Sharing = "none"
	Version_SharingDescendants Version_Sharing = "descendants"
	Version_SharingHierarchy   Version_Sharing = "hierarchy"
	Version_SharingTree        Version_Sharing = "tree"
	Version_SharingSystem      Version_Sharing = "system"
)

type Version struct {
	ID             int                `json:"id"`
	Project        *IDName            `json:"project,omitempty"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	Status         Version_Status     `json:"status"`
	DueDate        *string            `json:"due_date"`
	Sharing        Version_Sharing    `json:"sharing"`
	WikiPageTitle  *string            `json:"wiki_page_title"`
	EstimatedHours *float64           `json:"estimated_hours,omitempty"`
	SpentHours     *float64           `json:"spent_hours,omitempty"`
	CustomFields   []CustomFieldValue `json:"custom_fields,omitempty"`
	CreatedOn      time.Time          `json:"created_on"`
	UpdatedOn      time.Time          `json:"updated_on"`
}

type WikiPageSimple_Parent struct {
	Title string `json:"title"`
}

type WikiPageSimple struct {
	Title     string                 `json:"title"`
	Parent    *WikiPageSimple_Parent `json:"parent,omitempty"`
	Version   int                    `json:"version"`
	CreatedOn time.Time              `json:"created_on"`
	UpdatedOn time.Time              `json:"updated_on"`
}

type WikiPage_Parent struct {
	Title string `json:"title"`
}

type WikiPage struct {
	Title       string           `json:"title"`
	Parent      *WikiPage_Parent `json:"parent,omitempty"`
	Text        string           `json:"text"`
	Version     int              `json:"version"`
	Author      *IDName          `json:"author,omitempty"`
	Comments    *string          `json:"comments"`
	Project     *IDName          `json:"project,omitempty"`
	CreatedOn   time.Time        `json:"created_on"`
	UpdatedOn   time.Time        `json:"updated_on"`
	Attachments []Attachment     `json:"attachments,omitempty"`
}

type Query struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	IsPublic  bool   `json:"is_public"`
	ProjectID *int   `json:"project_id"`
}

type IssueStatus struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	IsClosed    bool    `json:"is_closed"`
	Description *string `json:"description"`
}

type Tracker struct {
	ID                    int      `json:"id"`
	Name                  string   `json:"name"`
	DefaultStatus         *IDName  `json:"default_status,omitempty"`
	Description           *string  `json:"description"`
	EnabledStandardFields []string `json:"enabled_standard_fields"`
}

type IssueCategory struct {
	ID         int     `json:"id"`
	Project    *IDName `json:"project,omitempty"`
	Name       string  `json:"name"`
	AssignedTo *IDName `json:"assigned_to,omitempty"`
}

type IssuePriority struct {
	ID           int                `json:"id"`
	Name         string             `json:"name"`
	IsDefault    bool               `json:"is_default"`
	Active       bool               `json:"active"`
	CustomFields []CustomFieldValue `json:"custom_fields,omitempty"`
}

type TimeEntryActivity struct {
	ID           int                `json:"id"`
	Name         string             `json:"name"`
	IsDefault    bool               `json:"is_default"`
	Active       bool               `json:"active"`
	CustomFields []CustomFieldValue `json:"custom_fields,omitempty"`
}

type DocumentCategory struct {
	ID           int                `json:"id"`
	Name         string             `json:"name"`
	IsDefault    bool               `json:"is_default"`
	Active       bool               `json:"active"`
	CustomFields []CustomFieldValue `json:"custom_fields,omitempty"`
}

type Role struct {
	ID                    int      `json:"id"`
	Name                  string   `json:"name"`
	Assignable            bool     `json:"assignable"`
	IssuesVisibility      string   `json:"issues_visibility"`
	TimeEntriesVisibility string   `json:"time_entries_visibility"`
	UsersVisibility       string   `json:"users_visibility"`
	Permissions           []string `json:"permissions"`
}

type GroupSimple struct {
	ID           int                `json:"id"`
	Name         string             `json:"name"`
	Builtin      *string            `json:"builtin,omitempty"`
	CustomFields []CustomFieldValue `json:"custom_fields,omitempty"`
}

type Group_Memberships_Item struct {
	ID      int              `json:"id"`
	Project IDName           `json:"project"`
	Roles   []MembershipRole `json:"roles"`
}

type Group struct {
	ID           int                      `json:"id"`
	Name         string                   `json:"name"`
	Builtin      *string                  `json:"builtin,omitempty"`
	CustomFields []CustomFieldValue       `json:"custom_fields,omitempty"`
	Users        []IDName                 `json:"users,omitempty"`
	Memberships  []Group_Memberships_Item `json:"memberships,omitempty"`
}

type CustomField_CustomizedType string

const (
	CustomField_CustomizedTypeIssue             CustomField_CustomizedType = "issue"
	CustomField_CustomizedTypeTimeEntry         CustomField_CustomizedType = "time_entry"
	CustomField_CustomizedTypeProject           CustomField_CustomizedType = "project"
	CustomField_CustomizedTypeVersion           CustomField_CustomizedType = "version"
	CustomField_CustomizedTypeDocument          CustomField_CustomizedType = "document"
	CustomField_CustomizedTypeUser              CustomField_CustomizedType = "user"
	CustomField_CustomizedTypeGroup             CustomField_CustomizedType = "group"
	CustomField_CustomizedTypeTimeEntryActivity CustomField_CustomizedType = "time_entry_activity"
	CustomField_CustomizedTypeIssuePriority     CustomField_CustomizedType = "issue_priority"
	CustomField_CustomizedTypeDocumentCategory  CustomField_CustomizedType = "document_category"
)

type CustomField_FieldFormat string

const (
	CustomField_FieldFormatEnumeration CustomField_FieldFormat = "enumeration"
	CustomField_FieldFormatString      CustomField_FieldFormat = "string"
	CustomField_FieldFormatVersion     CustomField_FieldFormat = "version"
	CustomField_FieldFormatAttachment  CustomField_FieldFormat = "attachment"
	CustomField_FieldFormatUser        CustomField_FieldFormat = "user"
	CustomField_FieldFormatList        CustomField_FieldFormat = "list"
	CustomField_FieldFormatLink        CustomField_FieldFormat = "link"
	CustomField_FieldFormatFloat       CustomField_FieldFormat = "float"
	CustomField_FieldFormatInt         CustomField_FieldFormat = "int"
	CustomField_FieldFormatDate        CustomField_FieldFormat = "date"
	CustomField_FieldFormatBool        CustomField_FieldFormat = "bool"
	CustomField_FieldFormatText        CustomField_FieldFormat = "text"
	CustomField_FieldFormatProgressbar CustomField_FieldFormat = "progressbar"
)

type CustomField_PossibleValues_Item struct {
	Value *string `json:"value,omitempty"`
	Label *string `json:"label,omitempty"`
}

type CustomField struct {
	ID             int                               `json:"id"`
	Name           string                            `json:"name"`
	Description    *string                           `json:"description"`
	CustomizedType *CustomField_CustomizedType       `json:"customized_type,omitempty"`
	FieldFormat    CustomField_FieldFormat           `json:"field_format"`
	Regexp         string                            `json:"regexp"`
	MinLength      *int                              `json:"min_length"`
	MaxLength      *int                              `json:"max_length"`
	IsRequired     bool                              `json:"is_required"`
	IsFilter       bool                              `json:"is_filter"`
	Searchable     bool                              `json:"searchable"`
	Multiple       bool                              `json:"multiple"`
	DefaultValue   *string                           `json:"default_value"`
	Visible        bool                              `json:"visible"`
	Editable       bool                              `json:"editable"`
	Trackers       []IDName                          `json:"trackers,omitempty"`
	Roles          []IDName                          `json:"roles,omitempty"`
	PossibleValues []CustomField_PossibleValues_Item `json:"possible_values,omitempty"`
}

type Search struct {
	ID          int       `json:"id"`
	Title       string    `json:"title"`
	Type        string    `json:"type"`
	URL         string    `json:"url"`
	Description *string   `json:"description"`
	Datetime    time.Time `json:"datetime"`
}

type File struct {
	ID           int       `json:"id"`
	Filename     string    `json:"filename"`
	Filesize     int       `json:"filesize"`
	ContentType  *string   `json:"content_type"`
	Description  *string   `json:"description"`
	ContentURL   string    `json:"content_url"`
	ThumbnailURL *string   `json:"thumbnail_url,omitempty"`
	Author       *IDName   `json:"author,omitempty"`
	CreatedOn    time.Time `json:"created_on"`
	Version      *IDName   `json:"version,omitempty"`
	Digest       string    `json:"digest"`
	Downloads    int       `json:"downloads"`
}

type MyAccount_User struct {
	ID           int                `json:"id"`
	Login        string             `json:"login"`
	Admin        bool               `json:"admin"`
	Firstname    string             `json:"firstname"`
	Lastname     string             `json:"lastname"`
	Mail         string             `json:"mail"`
	CreatedOn    time.Time          `json:"created_on"`
	LastLoginOn  *time.Time         `json:"last_login_on"`
	APIKey       string             `json:"api_key"`
	CustomFields []CustomFieldValue `json:"custom_fields,omitempty"`
}

type MyAccount struct {
	User MyAccount_User `json:"user"`
}
